CREATE TABLE APP (
    `APP_ID` INT,
    `APPNAME` VARCHAR(19) CHARACTER SET utf8
);
INSERT INTO APP VALUES (1,'catalog');
INSERT INTO APP VALUES (3,'favoritedestination');
INSERT INTO APP VALUES (4,'fuel');
