CREATE TABLE RL (
    `RL_ID` INT,
    `REGION` VARCHAR(2) CHARACTER SET utf8,
    `LANGUAGE` VARCHAR(2) CHARACTER SET utf8
);
INSERT INTO RL VALUES (1,'US','EN');
INSERT INTO RL VALUES (2,'FR','FR');
