CREATE TABLE STR_ID (
    `STR_ID` INT,
    `ST` VARCHAR(15) CHARACTER SET utf8
);
INSERT INTO STR_ID VALUES (1,'[HXH_MESSAGE]');
INSERT INTO STR_ID VALUES (2,'[OK]');
INSERT INTO STR_ID VALUES (3,'[VERSION]');
INSERT INTO STR_ID VALUES (4,'[CATALOG_HXH_1]');
INSERT INTO STR_ID VALUES (5,'[CATALOG_HXH_2]');
INSERT INTO STR_ID VALUES (6,'[CATALOG_HXH_3]');
INSERT INTO STR_ID VALUES (7,'[CATALOG_HXH_4]');
INSERT INTO STR_ID VALUES (8,'[CATALOG_HXH_5]');
INSERT INTO STR_ID VALUES (9,'[ADD_BUTTON]');
INSERT INTO STR_ID VALUES (10,'[EDIT_BUTTON]');
INSERT INTO STR_ID VALUES (11,'[FAVDEST_HXH_1]');
INSERT INTO STR_ID VALUES (12,'[FAVDEST_HXH_2]');
INSERT INTO STR_ID VALUES (13,'[FAVDEST_HXH_3]');
INSERT INTO STR_ID VALUES (14,'[FAVDEST_HXH_4]');
INSERT INTO STR_ID VALUES (15,'[FUEL_HXH_1]');
INSERT INTO STR_ID VALUES (16,'[FUEL_HXH_2]');
INSERT INTO STR_ID VALUES (17,'[FUEL_HXH_3]');
