CREATE TABLE Template (
    `PATH_ID` INT,
    `STR_ID` INT,
    `VALUE` INT
);
INSERT INTO Template VALUES (1,1,1);
INSERT INTO Template VALUES (1,2,3);
INSERT INTO Template VALUES (1,3,5);
INSERT INTO Template VALUES (1,4,6);
INSERT INTO Template VALUES (1,5,7);
INSERT INTO Template VALUES (1,6,8);
INSERT INTO Template VALUES (1,7,9);
INSERT INTO Template VALUES (1,8,10);
INSERT INTO Template VALUES (1,9,16);
INSERT INTO Template VALUES (1,10,6);
INSERT INTO Template VALUES (4,1,1);
INSERT INTO Template VALUES (4,2,3);
INSERT INTO Template VALUES (4,11,18);
INSERT INTO Template VALUES (4,12,19);
INSERT INTO Template VALUES (4,13,20);
INSERT INTO Template VALUES (4,14,21);
INSERT INTO Template VALUES (6,1,1);
INSERT INTO Template VALUES (6,2,3);
INSERT INTO Template VALUES (6,NULL,25);
INSERT INTO Template VALUES (6,15,26);
INSERT INTO Template VALUES (6,16,27);
INSERT INTO Template VALUES (6,17,28);
INSERT INTO Template VALUES (2,1,2);
INSERT INTO Template VALUES (2,2,4);
INSERT INTO Template VALUES (2,3,5);
INSERT INTO Template VALUES (2,4,11);
INSERT INTO Template VALUES (2,5,12);
INSERT INTO Template VALUES (2,6,13);
INSERT INTO Template VALUES (2,7,14);
INSERT INTO Template VALUES (2,8,15);
INSERT INTO Template VALUES (2,9,17);
INSERT INTO Template VALUES (2,10,11);
INSERT INTO Template VALUES (5,1,2);
INSERT INTO Template VALUES (5,2,4);
INSERT INTO Template VALUES (5,11,22);
INSERT INTO Template VALUES (5,12,23);
INSERT INTO Template VALUES (5,13,24);
INSERT INTO Template VALUES (5,14,21);
INSERT INTO Template VALUES (7,1,2);
INSERT INTO Template VALUES (7,2,4);
INSERT INTO Template VALUES (7,NULL,25);
INSERT INTO Template VALUES (7,15,29);
INSERT INTO Template VALUES (7,16,27);
INSERT INTO Template VALUES (7,17,30);
