CREATE TABLE VALUE (
    `VALUE` INT,
    `VALUE_ST` VARCHAR(57) CHARACTER SET utf8
);
INSERT INTO VALUE VALUES (1,'"Select app and choose command."');
INSERT INTO VALUE VALUES (2,'"Sélectionnez l''application et sélectionnez la commande."');
INSERT INTO VALUE VALUES (3,'"OK"');
INSERT INTO VALUE VALUES (4,'"D''accord"');
INSERT INTO VALUE VALUES (5,'"HXH"');
INSERT INTO VALUE VALUES (6,'"Edit"');
INSERT INTO VALUE VALUES (7,'"Remove"');
INSERT INTO VALUE VALUES (8,'"Save"');
INSERT INTO VALUE VALUES (9,'"Map"');
INSERT INTO VALUE VALUES (10,'"Label"');
INSERT INTO VALUE VALUES (11,'"modifier"');
INSERT INTO VALUE VALUES (12,'"Retirer"');
INSERT INTO VALUE VALUES (13,'"sauvegarder"');
INSERT INTO VALUE VALUES (14,'"Carte"');
INSERT INTO VALUE VALUES (15,'"Étiquette"');
INSERT INTO VALUE VALUES (16,'"Add"');
INSERT INTO VALUE VALUES (17,'"Ajouter"');
INSERT INTO VALUE VALUES (18,'"China"');
INSERT INTO VALUE VALUES (19,'"US"');
INSERT INTO VALUE VALUES (20,'"Austrilia"');
INSERT INTO VALUE VALUES (21,'"Japan"');
INSERT INTO VALUE VALUES (22,'"Chine"');
INSERT INTO VALUE VALUES (23,'"Nous"');
INSERT INTO VALUE VALUES (24,'"Australie"');
INSERT INTO VALUE VALUES (25,'<!--comment-->');
INSERT INTO VALUE VALUES (26,'"gasoline"');
INSERT INTO VALUE VALUES (27,'"diesel"');
INSERT INTO VALUE VALUES (28,'"electronic"');
INSERT INTO VALUE VALUES (29,'"de l''essence"');
INSERT INTO VALUE VALUES (30,'"electronique"');
